import "./bootstrap";
require("flatpickr/dist/themes/material_blue.css");
import Alpine from "alpinejs";
import flatpickr from "flatpickr";
import "flatpickr/dist/flatpickr.min.css";
window.Alpine = Alpine;
import "./../../vendor/power-components/livewire-powergrid/dist/powergrid";
import "./../../vendor/power-components/livewire-powergrid/dist/powergrid.css";
import SlimSelect from 'slim-select';
window.SlimSelect = SlimSelect;
Alpine.start();
