<x-app-layout>
    @can('super_admin.see.dashboard')
    @include('afac.dashboard.dashboard_superadmin')
    @endcan
    @can('user.see.navigation')
    @livewire('dashboard')
    @endcan
    @can('see.general.dashboard.except.admins')
    @include('afac.dashboard.dashboard_main')
    @endcan
</x-app-layout>